version: "3.8"
services:
  algorithm-fighter-mysql:
    image: bery0na/algofi-mysql:c5510edfc5e255057abd88608c3b1a660b1f99d3
    ports:
      - 3306:3306
    volumes:
      - mydata:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
    restart: always

  algorithm-fighter-core:
    image: bery0na/algofi-core:d6fe02b703c55f62b43530b928270fb7fcf21328
    ports:
      - 8080:8080
    environment:
      - DB_URL=algorithm-fighter-mysql
    depends_on:
      - algorithm-fighter-mysql
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 512M
    restart: on-failure

  algorithm-fighter-compile:
    image: bery0na/algofi-compile:887c996b2747ac127e89c3c5704f65af6652d1a7
    ports:
      - 9000:9000
    environment:
      - DB_URL=algorithm-fighter-mysql
    depends_on:
      - algorithm-fighter-mysql
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 512M
    restart: on-failure

  # algorithm-fighter-front:
  #   build: ./algorithm-fighter-front
  #   image: algofi-front-test:5.0.0-compose
  #   environment:
  #     - BACKEND_HOST=algorithm-fighter-core
  #   ports:
  #     - 80:3000
  #   depends_on:
  #     - algorithm-fighter-core
  #     - algorithm-fighter-compile
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.5"
  #         memory: 64M
  #   restart: on-failure

volumes:
  mydata:
